### ISSUE TITLE
Verification code should be required if you didn't pass ReCaptcha

### ISSUE THREAD

**Issue by MaksVeter** [wp-digital/wp-recaptcha#2]
After redirecting to "Verification code" screen, you can go to /wp-login.php and try one more time. So if you are on the fringe of threshold you can try several times to pass login without Verification code.
So probably Verification code should be required for user who didn't pass ReCaptcha for verification code lifetime.

**Comment by kuliebiakin** [comment]
Google will not increase user score in current session, so if it's a bot then it still will not be able to login, but the real user in that time could open login page from anywhere else, so we do not need to block him.

But maybe it's an idea to block only by IP address + lifetime, need to thinking about that.

**Comment by MaksVeter** [comment]
done on branch `feature/ip_blocking`
@kuliebiakin pls check

**Comment by kuliebiakin** [comment]
Merged.
