### ISSUE TITLE
Add allow list of IPs

### ISSUE THREAD

**Issue by kuliebiakin** [wp-digital/wp-recaptcha#3]
Add possibility to allow certain number of IPs.
It would be good to integrate with Cloudflare Firewall.

**Comment by MaksVeter** [comment]
done on branch `feature/allow_ip_list`
@kuliebiakin pls check.

**Comment by kuliebiakin** [comment]
@MaksVeter, please check:
1. Remove this https://github.com/innocode-digital/wp-recaptcha/blob/feature/allow_ip_list/wp-recaptcha.php#L54
2. This https://github.com/innocode-digital/wp-recaptcha/blob/feature/allow_ip_list/src/Plugin.php#L125 performs remote request every hour for some random user on site because it's calling on `init` action. For me it looks that better to do this request on cron and maybe through some manual action in admin panel.

**Comment by MaksVeter** [comment]
fixed, pls check

**Comment by kuliebiakin** [comment]
Developed new version of plugin with static and configurable Allow Lists support.

Also, new version supports Cloudflare Turnstile which may be used instead of Google reCAPTCHA v3.

Integration with Cloudflare's WAF removed because it's in general looks complex as requires checking and syncing of hundreds of rules, so I think it's too complicated for as integration for such plugin. It should be enough to have constant and admin panel option (**Settings** -> **Bot Protection**) to handle such functionality as Allow List.

I'll deploy new version with https://github.com/wp-digital/diverse/issues/348.

Good to close.
